name: Automated Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load code
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test -- --ci --reporters=default --reporters=jest-junit
      - name: Reports the results of tests
        uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          run-name: test
